// var templates = {};
//
// templates.calc = [
//   '<ul>',
//     '<li id="clear">C</li>',
//     '<li id="input"></li>',
//   '</ul>',
//   '<ul>',
//     '<li class="calButton">7</li>',
//     '<li class="calButton">8</li>',
//     '<li class="calButton">9</li>',
//     '<li class="calButton">/</li>',
//   '</ul>',
//   '<ul>',
//     '<li class="calButton">4</li>',
//     '<li class="calButton">5</li>',
//     '<li class="calButton">6</li>',
//     '<li class="calButton">X</li>',
//   '</ul>',
//   '<ul>',
//     '<li class="calButton">1</li>',
//     '<li class="calButton">2</li>',
//     '<li class="calButton">3</li>',
//     '<li class="calButton">-</li>',
//   '</ul>',
//   '<ul>',
//     '<li class="calButton">0</li>',
//     '<li class="calButton">.</li>',
//     '<li id="evaluateCalc">=</li>',
//     '<li class="calButton">+</li>',
//   '</ul>'
// ].join("");
